name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./application/package.json
      - run: pnpm install
      - run: pnpm web lint

  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./application/package.json
      - run: pnpm install
      - run: pnpm web test

  typecheck-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./application/package.json
      - run: pnpm install
      - run: pnpm web typecheck
