name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: 
      name: prod
    defaults:
      run:
        working-directory: ./packages/web
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.WRANGLER_JSON }} > ./wrangler.json
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
